SUPPORTED_FILE_TYPES = {".csv", ".xlsx", ".xls"}

MAX_PREVIEW_ROWS = 5
MAX_CATEGORIES_FOR_ENCODING = 20
PCA_VARIANCE_THRESHOLD = 0.95

AVAILABLE_ALGORITHMS = ["KMeans", "AgglomerativeClustering"]

DEFAULT_K_RANGE = (2, 10)
